version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  ghost:
    image: 'bitnami/ghost:0'
    ports:
      - '80:2368'
    volumes:
      - 'ghost_data:/bitnami/ghost'
    depends_on:
      - mariadb
    environment:
      - GHOST_HOST=localhost
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
